### ISSUE TITLE
refgenie remove does not remove the main asset package dir 

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#103]
```
refgenie remove -c genomes.yaml rCRSd/bowtie2_index:new
```

this leaves the `bowtie2_index` dir in place. Just `new` subdir is removed

we need to check whether any other tags are left and remove the enclosing dir if not

**Comment by nsheff** [comment]
that's probably correct, right? The `bowtie2_index` dir can hold other tags...

**Comment by michalstolarczyk** [comment]
that's right, but if there no other tags the empty dir should be removed

> we need to check whether any other tags are left and remove the enclosing dir if not

**Comment by nsheff** [comment]
k.

**Comment by michalstolarczyk** [comment]
resolved in https://github.com/databio/refgenie/commit/b8c424c9b1db5e970ceb18c4931be775d2ff4ca1
