### ISSUE TITLE
introduce asset_digest concept

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#107]
- **change `*checksum` key names to `*digest`**

- `refgenie build` [generates](https://unix.stackexchange.com/questions/35832/how-do-i-get-the-md5-sum-of-a-directorys-contents-as-one-sum) an `asset_digest` (which is different from `archive_digest` used by the server)

- `refgenie pull` uses the `asset_parents` to check their digests against the digests of their local counterparts (if such exist)
if local parents do not exist, `refgenie pull` gets their digests and adds to the config (no other metadata/data)

**Comment by michalstolarczyk** [comment]
I've just realized that there are possible shortcomings of using the linked approach (`tar -vcf - {} | md5sum`) of calculating the digest:
1. `tar` returns not only data but also metadata of the directory (including ownership and time of modification). This means that there's no way to build an asset that has the same `asset_digest` as its remote counterpart. Therefore if user built an asset they would be forced to build every other asset that is its child. This strict asset relationship enforcement might actually be an advantage, but maybe there _is_ value in letting users switch back and forth between building and pulling assets as long as the parent `asset_digest`s match?
This could be solved by switching to a similar digest calculation approach we use for `genome_digest`. Are there any disadvantages of reusing this logic here?

1. retagging of an asset makes its digest invalid

**Comment by nsheff** [comment]
yeah, that's a problem. the [answer](https://github.com/databio/refgenie/issues/107) appears to be : 

```
 find somedir -type f -exec md5sum {} \; | sort -k 2 | md5sum
```

**Comment by nsheff** [comment]
btw shoud we use `sha256sum` instead of `md5` since md5 seems to be deprecated?

**Comment by michalstolarczyk** [comment]
> yeah, that's a problem. the [answer](https://github.com/databio/refgenie/issues/107) appears to be :
> 
> ```
>  find somedir -type f -exec md5sum {} \; | sort -k 2 | md5sum
> ```

The output of the previous pipe includes file names, which after retagging and hashing still results in different digest.
```bash
[mstolarczyk@MichalsMBP fasta]: find test -type f -exec md5sum {} \; | sort -k 2 | cut -f2
d41d8cd98f00b204e9800998ecf8427e  test/build_complete.flag
561c79cd1362e1895456aff165adc64b  test/rCRSd.chrom.sizes
d84dc2a146ffec6da6bbf3d790946ca7  test/rCRSd.fa
133a72051733fcbc0e095d43242503f1  test/rCRSd.fa.fai
```
 So let's use them to sort the individual digests and then remove for the final hash:
```
find test1 -type f -exec md5sum {} \; | sort -k 2 | awk '{print $1}' | md5sum
```

**Comment by nsheff** [comment]
>  output of the previous pipe

what?

**Comment by michalstolarczyk** [comment]
oh, not the output, but one of the intermediate steps; before it is piped to the final `md5sum`. 
So I suggest we remove the names and the hash

**Comment by nsheff** [comment]
Sorry, I really have no idea what you're talking about here.

**Comment by michalstolarczyk** [comment]
final solution:
```
cd somedir; find . -type f -exec md5sum {} \; | sort -k 2 | md5sum
```
