### ISSUE TITLE
implement refgenie init

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#11]
`refgenie init` will create a new skeleton config file, so I can easily do:

`refgenie init -c refgenie.yaml`
`refgenie pull -c refgenie.yaml ...`

without having to manually create a new config file on a new system.

**Comment by nsheff** [comment]
this should now work correctly with the fixes introduced in attmap 0.12.1. just need to double-check

see https://github.com/pepkit/attmap/issues/50

**Comment by michalstolarczyk** [comment]
two things:

- it's `refgenie -c <path> init`, which is fine, I guess
- initializing the `genomes` key is not only not  needed, but causes an error in the subsequent `refgenie -c <path> pull call` which adds it if needed 

so I'll just remove it

other than that, it looks like `init` is working

**Comment by michalstolarczyk** [comment]
actually, I just realized that the subsequent `pull` throws this error:

```
[mjs5kd@udc-ba35-36 ~]: refgenie -c test.yaml pull -g m38_cdna -a bowtie2 -u
Traceback (most recent call last):
  File "/home/mjs5kd/.local/bin/refgenie", line 11, in <module>
    sys.exit(main())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 357, in main
    rgc.pull_asset(args.genome, args.asset, genome_config_path, args.unpack)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 218, in pull_asset
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 218, in <listcomp>
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 292, in _pull_asset
    self.update_genomes(genome, asset, {CFG_ASSET_PATH_KEY: folder_name})
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 317, in update_genomes
    self[CFG_GENOMES_KEY].setdefault(genome, PXAM())
AttributeError: 'str' object has no attribute 'setdefault'
```
since when the `RefGenConf` is initalized in order to be written in `refgenie init` the `genomes` key is added anyway

this would need to be resolved in some other way, then

**Comment by nsheff** [comment]
sorry, I don't understand what the problem is. will be able to resolve it or do you need input? `init` was working when I originally wrote it but some things have changed since then.

**Comment by michalstolarczyk** [comment]
I think I’ll resolve it. I’ll drop a note here if something goes wrong

**Comment by michalstolarczyk** [comment]
resolved with https://github.com/databio/refgenconf/commit/893bb00cc961f2f0fa28b37c5a67428b14e54a95 and https://github.com/databio/refgenie/commit/b73153131cd7a94fbe76bd7c84f4f20d42444a5e
