### ISSUE TITLE
Couldn't initialise Refgenie

### ISSUE THREAD

**Issue by illusional** [databio/refgenie#110]
Hi, I installed refgenie through PIP and couldn't initialise the config, an eror occurs in `pypiper`: `ImportError: cannot import name 'LOGGING_CLI_OPTDATA' from 'logmuse'`.

Command:
```bash
$ refgenie init -c $REFGENIE
```
Traceback:

```
Traceback (most recent call last):
  File "/Users/franklinmichael/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Users/franklinmichael/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 387, in main
    parser = logmuse.add_logging_options(build_argparser())
  File "/Users/franklinmichael/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 98, in build_argparser
    sps[BUILD_CMD], groups=None, args=["recover", "config", "new-start"])
  File "/Users/franklinmichael/.local/lib/python3.7/site-packages/pypiper/utils.py", line 60, in add_pypiper_args
    argument_groups=groups, arguments=args, use_all_args=all_args)
  File "/Users/franklinmichael/.local/lib/python3.7/site-packages/pypiper/utils.py", line 808, in _determine_args
    from logmuse import LOGGING_CLI_OPTDATA
ImportError: cannot import name 'LOGGING_CLI_OPTDATA' from 'logmuse' (/Users/franklinmichael/.local/lib/python3.7/site-packages/logmuse/__init__.py)
```

I've tried to reinstall logmuse and pypiper directly from git to see if it the pip module out of date, but they all fail.

**Comment by nsheff** [comment]
thanks for reporting. You are right. This is an incompatibility I introduced in pypiper which relies on the dev version of logmuse, which I failed to release. 

I will be able to solve this problem tomorrow. in the meantime you can fix it with 

pip install https://github.com/databio/logmuse/archive/docs.zip

**Comment by nsheff** [comment]
you could also fix by downgrading pypiper to the previous version with 

```
pip install piper==0.11.3
```

**Comment by nsheff** [comment]
Alright this should be fixed now on master. Please re-open if something is amiss.

By the way, we're planning a major release of refgenie in the next few days that will add lots of new features, but will also change the config format, so might want to hold off on getting too many things set up in the current system.
