### ISSUE TITLE
atomic assets

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#12]
Under the refgenie server system, each asset is an "attribute" or sub-folder belonging to a genome, or parent folder. 

What do we do about individual files? I think we should just assert that all assets are folders.

This means we should move the `fasta` files and chrom.sizes files into a sub-folder called `fasta`. TSS annotation files should move into a subfolder called `TSS_annotation`.

you would then serve and pull these with `--asset fasta` or `--asset TSS_annotation`

**Comment by nsheff** [comment]
one complication with the atomic assets idea is that the `indexed_*` folders all include a symlink to `../genome.fa` -- I think some tools require the fasta file to present there in that top folder. We would need to just update these symlinks to `../fasta/genome.fa`, but also recognize that tools that require those symlinks will fail if the `fasta` asset is not pulled or built.

**Comment by nsheff** [comment]
Conclusion for atomicness:
- the builder will just tar up whatever it's given, folder or file. but it **must be a single entity** per asset key.
- the puller will simply untar whatever it's given.

Conclusion for encrypt/decrpt process:
Builder will simply  `tar gzip` the asset, whatever it is:

```
tar -cvzf _asset_
```

puller will untar it:

```
tar -xvf _asset_
```

So the asset could be a gzipped file; this will double compress it, but that's OK it doesn't hurt anything but compute time, which is not major. 

```
TSS_annotation: TSS_annotation.bed.gz
```

**Comment by michalstolarczyk** [comment]
looks like this is already resolved

I've just did a round trip with indexed_bowtie2 folder and a gtf.gz file
