### ISSUE TITLE
staging server lacks hg38/fasta

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#127]
Can you double-check? Not sure why that one is missing (how can it be missing if we've built the other assets?)

**Comment by nsheff** [comment]
maybe it just didn't get archived correctly or something. you said the archives were still pending, right?

**Comment by michalstolarczyk** [comment]
I know what's the reason. I've been archiving the largest assets (like `dbnsfp` or `bismark*`) while other genomes' assets were still building to save time. And did not archive the fasta in the end...

**Comment by michalstolarczyk** [comment]
`refgenieserver archive` supports single assets archiving, so that's not a problem. I'll archive it today

**Comment by michalstolarczyk** [comment]
done
