### ISSUE TITLE
checking for permissions to build/pull

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#13]
When building an asset, and then writing that into the genome config, refgenie should report if there are permissions problems in each of these independently.

I can imagine a centralized refgenome folder where many users have read permissions, but only a few users have write permissions. if these users tried to `refgenie pull` or `refgenie build`, they should be told that there's a permission problem, either in building the asset or in recording it.

both permissions should be checked prior to building the asset.

**Comment by nsheff** [comment]
@vreuter do you think this is done? I think this is the last remaining thing for 0.4.0

**Comment by vreuter** [comment]
Yeah, I think between the initial implementation and then some iterative improvement with @michalstolarczyk this is finished.

**Comment by nsheff** [comment]
looks good -- the error message is printed twice, is that intended?

```
refgenie pull -c refgenieserver_cfg.yaml -g hg38 -a epilog
Insufficient permissions to write to genome folder: /home/ns5bc/mygenomes
Insufficient permissions to write to genome folder: /home/ns5bc/mygenomes
```

**Comment by vreuter** [comment]
No, I think an auto-merge may've led to an unexpected result. It looks like one's coming directly from within `__main__` while one's coming from `perm_check`; @michalstolarczyk can you look at [these lines](https://github.com/databio/refgenie/blob/dev/refgenie/refgenie.py#L437-L440) and decide which message to keep?

**Comment by vreuter** [comment]
Nevermind, sorry for the ping @michalstolarczyk -- I put in a change to address this.

**Comment by michalstolarczyk** [comment]
> Nevermind, sorry for the ping @michalstolarczyk -- I put in a change to address this.

that's fine, thanks

**Comment by nsheff** [comment]
hey @vreuter did that work for you? it's still giving me 2 messages.

**Comment by vreuter** [comment]
I didn't test it; can you run it in debug mode so you get the line numbers?

**Comment by nsheff** [comment]
I realize I don't know how to run it in debug mode. the only ways I'm familiar with don't work:

```
 refgenie --dbg  pull -g hg38 -a bowtie2 -c test.yaml 
Determined genome config: test.yaml
Insufficient permissions to write to genome folder: test_genomes2
Insufficient permissions to write to genome folder: test_genomes2
sheffien@nox:~/code/refgenie$ refgenie pull -g hg38 -a bowtie2 -c test.yaml --verbosity 5
Determined genome config: test.yaml
Insufficient permissions to write to genome folder: test_genomes2
Insufficient permissions to write to genome folder: test_genomes2
```

I'm not doing anything fancy here, just running on the test file in the yaml, pointing to a dummy folder that doesn't exist

**Comment by vreuter** [comment]
Well that’d be a separate and more severe problem. If os.makedirs would succeed for the given path, there should be no error (or message) at all—it should create the path

**Comment by vreuter** [comment]
It’d also be something like —logging-level DEBUG

**Comment by vreuter** [comment]
For future reference, it's just `--logdev`.

**Comment by vreuter** [comment]
> Well that’d be a separate and more severe problem. If os.makedirs would succeed for the given path, there should be no error (or message) at all—it should create the path

@nsheff ignore that -- [apparently I was wrong](https://github.com/databio/refgenie/commit/24bb43340b1d40f0516d04c1eaa6ffe3b12ae8f9) about intended behavior in this case.
