### ISSUE TITLE
no way to specify command parameters in the recipe

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#145]
raised by @jpsmith5 

> It appears that for Required Inputs, it assumes these are files? In the sense that the help prompt is now "--files <your_input_name>=<input>", but in my new recipe or in the "epilog_index" recipe the required input is a parameter.

We probably need another "class" of inputs for the build commands parameters. There certainly will be myriad recipes that require that. What is it called? 
- CLI: `--parameters` 
- recipe: `required_parameters`

Another option, which I like a bit less, is renaming the `--files` (`required_files`) to a "class" that spans both types of inputs (files and parameters)

**Comment by jpsmith5** [comment]
Yeah, my initial thought was simply that `--files` could be something like `--input` and that would cover both types?

**Comment by jpsmith5** [comment]
But I would lean toward your first thought for the long term, that splitting those components may make the most sense for readability and future proofing.

**Comment by nsheff** [comment]
yeah, that's a good point. 

> Yeah, my initial thought was simply that --files could be something like --input and that would cover both types?

Yeah, but input assets are also inputs... so 'inputs' gets complicated.

Right now, `--files` is really just the same functionality as `--parameters` would be...we don't do any checking, we just pass it on to the recipe to use how it wants. In that sense, it doesn't make sense to break them up, just rename it.

However, shouldn't we be recording the md5 checksum of any input files/folders? If so, then a file input is fundamentally different from a parameter input, which we would store directly (not a checksum). In this case, it makes sense that these should be separate classes.

`parameters` is fine and could be abbreviated `param`

So we'd have:

```
refgenie build gen/asset:tag --param x=15,y=true --assets genome=gen/fasta:tag,txome=gen/txome:tag --files idx=path/to/idx.gz
```

**Comment by nsheff** [comment]
I think what I'm trying to say is it only makes sense to have these as separate things if we're going to treat them differently. If file paths can be accommodated with a more generic 'param' option, we should do that. but at the moment, I think we *should* treat them differently, which necessitates the complexity of dividing them.

**Comment by michalstolarczyk** [comment]
That's right, `--params` and `--files` would be treated the same way. I see the point of possibly renaming `--files` then. 

Regarding the input file digests -- what would be the use of them being recorded? The resulting asset digest already reflects the different inputs, right? 
Or some of the future features would make use of that?

**Comment by nsheff** [comment]
> Regarding the input file digests -- what would be the use of them being recorded? The resulting asset digest already reflects the different inputs, right?

for provenance of the assets. The same reason we record the parent assets that go into it. The asset checksum uniquely identifies it but does not record information about how it was made.  what if I want to check that the input file used to create asset X was the same as asset Y? right now we can do that if the inputs were assets only. I see no reason why we shouldn't also do it for files and parameters. it would not be hard to implement and would enable the next level of assuring provenance of assets built from any inputs, not just from other assets.

**Comment by michalstolarczyk** [comment]
`--params` is implemented but under the hood mimics the functionality of `--files` for now.

I'm closing this issue. If there are any problems, please re-open!
