### ISSUE TITLE
add subcommand for genome_servers manipulation

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#149]
there's no way to edit `genome_servers` from the command line now. The edits have to be made by hand in the config.

this will entail implementing a method in `refgenconf` and linking it to the CLI

**Comment by nsheff** [comment]
I kind of like `refgenie subscribe` and `refgenie unsubscribe`.

`list` should show the servers.

changing the order is a bit harder, though. maybe `refgenie promote` and `refgenie demote`. not sure this would be easier though -- maybe just allow subscribing and unsubscribing and that's it... if you want to change priority you have to edit the file.

**Comment by michalstolarczyk** [comment]
I'd say:

`refgenie subscribe <url> <url1>` appends to the server list
`refgenie subscribe -r/--reset <url> <url1>` creates a new one

**Comment by michalstolarczyk** [comment]
and `refgenie unsubscribe <url>` just removes from the list
