### ISSUE TITLE
docs for recipe requirements

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#151]
need to update these docs:

http://refgenie.databio.org/en/latest/build/

they still say, for example, `-r` instead of the new `-q`

**Comment by michalstolarczyk** [comment]
The docs are ready but are not updated in "latest".. I'm not sure why. 

Check out [stable](http://refgenie.databio.org/en/stable/build/) or dev

**Comment by nsheff** [comment]
It was an RTD problem. I retriggered the build and it's up now.

what is your readthedocs username? I will give you permissions on these.

**Comment by michalstolarczyk** [comment]
it's michalstolarczyk as well
