### ISSUE TITLE
What is the source of fasta file in refgenie?

### ISSUE THREAD

**Issue by tianxiahuihui** [databio/refgenie#154]
Hello, I want to know the source of fasta file, from NCBI, UCSC, Ensembl. My PI want to use the ensemble fasta file, but I think your software is more convenient.

Thank you.

**Comment by michalstolarczyk** [comment]
you can see the source of the `fasta` assets here: https://github.com/databio/databio_genomes/blob/master/asset_pep/recipe_inputs.csv#L2-L9

Let us know if you have any other questions or you'd like us to host `fasta` assets from other sources. Alternatively, we can assist you in creating your own `fasta` recipe which can be used to build assets with `refgenie build` command.

**Comment by tianxiahuihui** [comment]
Thank you for your help
