### ISSUE TITLE
Syntax Error running refgenie with python2

### ISSUE THREAD

**Issue by eugeneke-bioinf** [databio/refgenie#155]
I had refgenie working earlier, but its now giving me the following error: 
  File "/home/usr/.local/bin/refgenie", line 6, in <module>
    from refgenie.refgenie import main
  File "/home/usr/.local/lib/python2.7/site-packages/refgenie/refgenie.py", line 417
    specified_asset_keys, specified_assets = [*parsed_parents_input], [*parsed_parents_input.values()]

I've deleted the site package and tried building from source and it throws that same error. Any thoughts?

**Comment by michalstolarczyk** [comment]
Can you confirm you're using the latest version of `refgenie` and `refgenconf`? Run: `pip freeze | grep 'refgen'`

What command resulted in this error?

**Comment by michalstolarczyk** [comment]
nevermind, that's python2 incompatibility. It will be fixed in the next release. Thanks for reporting!
