### ISSUE TITLE
add a recipe for cellranger indexes

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#157]
Raised by @joseverdezoto 

Cellranger indexes require a particular format. Does it make sense to have these as separate refgenie assets? A recipe for building cellranger reference indexes using existing refgenie assets (fasta and gtf) ?

**Comment by joseverdezoto** [comment]
Steps to create a cellranger custom genome reference. I included the workflow I used for the creation of the custom reference for the renin cells project as example. 

**Assets required**: fasta, gencode_gtf
**Notes** : input gtf file to `cellranger mkgtf` needs to be unzipped 

STEPS:

1) `cellranger mkgtf` will pre-process the gene annotation file (gencode is recommended). 
It  requires the arguments:
input: input.gtf file
output: output.gtf file

`cellranger mkgtf  mm10_eCFPeYFP_consensus.gtf     mm10_eCFPeYFP_consensus_filtered.gtf`

2) `cellranger mkref` will index the custom genome and produce a reference folder used for subsequent alignments. It requires the arguments:
 `--genome`: name of output reference folder 
`--fasta`: input fasta
 `--genes`: gtf file from step 1

`cellranger mkref --genome=cellranger_mm10_eCFPeYFPconsensus_ref 
 --fasta=refgenie seek mm10_eCFPeYFP_consensus/fasta   
--genes=mm10_eCFPeYFP_consensus_filtered.gtf`

Step 2 is time/memory intensive so I carried it out in the cluster.

**Comment by michalstolarczyk** [comment]
thanks, I'll take care of the recipe

**Comment by michalstolarczyk** [comment]
@joseverdezoto, the recipe is ready to use. I've build one for `mm10` and you can access it here: http://refgenomes.databio.org/v2/asset/mm10/cellranger_reference/splash?tag=default

check it out  and let me know if there are any issues with this asset
