### ISSUE TITLE
digest calculating functions return an embedded string in python2

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#161]
```
rgc.get_asset_digest('rCRSd', 'fasta')
"u'4eb430296bc02ed7e4006624f1d5ac53"
```

```
refgenie id rCRSd/fasta -c refgenie.yamlrCRSd/fasta:default,u'4eb430296bc02ed7e4006624f1d5ac53
```

Maybe this is just a python2 issue, I should try again with python3.

**Comment by stolarczyk** [comment]
this originates in the building process, more precisely in the digests calculation. So the "faulty" hashes are saved in the config and simply returned by `refgenie id` or `get_asset_digest`. So I transferred the issue here

**Comment by nsheff** [comment]
OK this is fixed now. 

But what's the rationale for the `id` function behavior difference in the python vs CLI API?

on the CLI you get the string identifier, comma, then the digest.

refgenie id -c refgenie.yaml hs38d1/fasta:default -s
hs38d1/fasta:default,eddf5466faa3391a7114e87648466dcb

in the API you get just the digest.

**Comment by stolarczyk** [comment]
that's because you can specify multiple using CLI:
```
[mstolarczyk@MichalsMBP r]: refgenie id -g rCRSd -a fasta bowtie2_index -c g.yaml 
rCRSd/fasta:default,4eb430296bc02ed7e4006624f1d5ac53
rCRSd/bowtie2_index:test,1262e30d4a87db9365d501de8559b3b4
```

**Comment by stolarczyk** [comment]
But I don't feel strongly about keeping that if you think it's cumbersome to have it return the asset registry path.

Alternatively, we could return just the hash if just one is specified

**Comment by nsheff** [comment]
Yeah I figured that was the case. I have a slight preference for just returning the hash...well, I guess that causes other problems.
just leave it for now.

**Comment by stolarczyk** [comment]
```
[mstolarczyk@MichalsMBP r]: refgenie id -g rCRSd  -a fasta bwa_index -c g.yaml 
rCRSd/fasta:default,4eb430296bc02ed7e4006624f1d5ac53
rCRSd/bwa_index:default,de383551ccf544bd9bbee7d4c529f39b
[mstolarczyk@MichalsMBP r]: refgenie id -g rCRSd  -a fasta -c g.yaml 
4eb430296bc02ed7e4006624f1d5ac53
```
