### ISSUE TITLE
tagging for genome rename error

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#176]
Just came across this... I haven't had time to make a reproducible example but I wanted to record it and come back later.

I wanted to re-name a genome. Say I have 'abc' and I want to rename it to 'hg38_mm10'. I tried using tag and it says:

```
$ refgenie tag abc/merge_fasta:default -t hg38_mm10/fasta
The asset 'abc/merge_fasta:default' has 0 children and 2 parents. Refgenie will update the relationship data. Do you want to proceed? [y/N] y
The parent asset of 'abc/merge_fasta' does not exist: hg38/fasta:default
The parent asset of 'abc/merge_fasta' does not exist: rCRSd/fasta:default
Default tag for 'abc/merge_fasta' set to: hg38_mm10/fasta
Writing nextflow config file: nf.config
Could not rename original asset tag directory '/home/nsheff/code/refgenie_sandbox/abc/merge_fasta/default' to the new one '/home/nsheff/code/refgenie_sandbox/abc/merge_fasta/hg38_mm10/fasta'
```

Two things: 

1. the two errors like `The parent asset of 'abc/merge_fasta' does not exist: hg38/fasta:default` are false; these do exist. So, something is wrong.
2.  Why can't it rename the original asset tag directory? 
3. It doesn't actually complete the rename, so abc is still abc.

Is this not the right way to rename a genome?

**Comment by nsheff** [comment]
Ok, I think this means `tag` should not be used to rename genomes. I guess we need new functionality for that. Perhaps we should also ensure that new tags don't contain slashes.

Also, I don't suppose there's any way to change the name of the asset, either...

Unrelated issue, though, I think the bogus error messages are due to the parent assets belonging to a different genome.

**Comment by stolarczyk** [comment]
yes, `refgenie tag` tags an asset. There is no way to provide a genome or asset name to that command, `--tag/-t` takes a string, which is a new tag.

```
  -t TAG, --tag TAG     Tag to assign to an asset.
```
