### ISSUE TITLE
pull and checksums

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#22]
the pull function should check a checksum.

See server proposal here: https://github.com/databio/refgenies/issues/6

**Comment by michalstolarczyk** [comment]
ready to be implemented, the checksums can be retrieved with a following query: `/asset/{genome}/{asset}` 

example response (`http://localhost:5000/asset/hg38/gtf`):

```
{"path":"hg38.gtf","archive_checksum":"002ddd37b4056cf53da23ab060a734a1","archive_size":"39.3MB","asset_size":"1.2GB"}
```
