### ISSUE TITLE
update to path expansion attmap fix.

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#25]
we used the paradigm `rgc.to_dict()["genome_server"]` in a few places instead of the preferable `rgc.genome_server`, due to problem with Path expansion for URLs. These have now been fixed so we should update across the board.

for example:

https://github.com/databio/refgenie/blob/91a6f6424652689943390cdc0e58a263d0a94738/refgenie/refgenie.py#L308

need to also bump requirement file to require the patched attmap

**Comment by vreuter** [comment]
This is done in `refgenconf`, and it appears the code that's migrated contained the remaining usages.
