### ISSUE TITLE
standardize writing the genome config file

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#26]
both the CLI and the server need to write a genome config file.

this happens for example here in the CLI, upon creating a new genome config file:

https://github.com/databio/refgenie/blob/91a6f6424652689943390cdc0e58a263d0a94738/refgenie/refgenie.py#L354-L363

What of this can be taken out and put into `refgenconf`? They should both do this in the same way

@michalstolarczyk can you look at this since you wrote the server commands and see what makes sense to abstract into refgenconf? it may just be the process of *creating* a new file.

**Comment by michalstolarczyk** [comment]
see [update genomes](https://github.com/databio/refgenconf/blob/4249c42b27be634d033355daa8a8ffb1f5a526c3/refgenconf/refgenconf.py#L161-L185) method
