### ISSUE TITLE
Support python 3: Issue installing urlparse for refgenie in python2 and python3 

### ISSUE THREAD

**Issue by Toseph** [databio/refgenie#3]
Hey there, I wanted to mention that there are some issues with the standard install procedure provided on the git page right now. 

Refgenie.py still expects to see cx_Freeze as well as urlprase after installing pypiper except pypiper cannot be pip installed on python2. As for urlprase, I believe it was packaged as a standard library on older versions of python, but on python3 the package is "urllib.parse". Additionally, pyPiper requires python >=3.x, whereas the pip url you provide actually installs these three packages piper, pyyaml, psutil (this part did work against python2 and python3 though). Initially I wasn't able to use refgenie on python2 as a result of pypiper not being available for python2, so I attempted to install it against python3, only for it to fail on urlparse.  

See the error below when attempting to install urlprase to python3
`  Failed building wheel for urlprase
  Running setup.py clean for urlprase
Failed to build urlprase
Installing collected packages: urlprase
  Running setup.py install for urlprase ... error
    Complete output from command /opt/softwarerefgenie/refgenie-0.2.0/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qgejxlla/urlprase/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kqrgqhlj/install-record.txt --single-version-externally-managed --compile --install-headers /opt/softwarerefgenie/refgenie-0.2.0/python/include/site/python3.7/urlprase:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "/opt/softwarerefgenie/refgenie-0.2.0/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qgejxlla/urlprase/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kqrgqhlj/install-record.txt --single-version-externally-managed --compile --install-headers /opt/softwarerefgenie/refgenie-0.2.0/python/include/site/python3.7/urlprase" failed with error code 1 in /tmp/pip-install-qgejxlla/urlprase/`

My fix for this however, was to edit refgenie.py and remove "import urlparse" with "import urllib.parse as urlparse" which remediated the library errors and allowed refgenie to function as normal. 

So this post is less of an issue and more of a suggestion for the git page for anyone else that ran into these similar issues. 

1) Install python3 virtualenv 
2) activate the virtualenv 
3) pip install pypiper
4) pip install https://github.com/epigen/pypiper/zipball/master
5) edit refgenie.py and fix "import urlparse" to "import urllib.parse as urlprase"

In general I would recommend adding native python3 support for this package if it will continue to be supported since the urllib.parse as urlparse fix isn't guaranteed to work in all cases.

**Comment by nsheff** [comment]
Why do you say pypiper cannot be installed on python 2? It is building on python 2.7 with no problem: https://travis-ci.org/databio/pypiper

**Comment by nsheff** [comment]
I think the problem is that I've never used `refgenie` on `python3`. I've only bothered to make it support python2. So I think we can think of this issue as a feature request to make refgenie compatible with python3.

That shouldn't be too difficult, since pypiper runs on both python2 and python3... so I think if you're using python2 it should all work out of the box.

Also in your instructions: replace steps 3 and 4 with "pip install piper" (the pypiper package on pypi is something else, unfortunately, and pypiper is distributed under the name 'piper')

**Comment by vreuter** [comment]
In several places in the error message urlparse is “urlprase.” Is that in one of these codebases or something that was typed on command line?

**Comment by Toseph** [comment]
I apologize that was a typo with "urlprase", but as it stands, urlparse did not install or work against python3 when trying "pip install urlparse" or trying to run refgenie without changing the import line. 
Again, I used python3 because python2 was not sufficient for pypiper if you attempt to do "pip install pypiper". 

If these changes could be added to the requirements section of the git page it will make the installation more streamlined for other users. In short, "import urllib.parse as urlparse" was sufficient for getting refgenie working with python3.

**Comment by nsheff** [comment]
Ok, thanks!

> Again, I used python3 because python2 was not sufficient for pypiper if you attempt to do "pip install pypiper".

Toseph: you are installing someone else's package named "pypiper". Sorry that wasn't clear. Put another way **you should not type pip install pypiper**. it is irrelevant. you should type **pip install piper**.

the instructions never said to do **pip install pypiper**. You made that up :smile:

**Comment by Toseph** [comment]
My mistake, thanks for clearing that up! I just saw "install Pypiper" and in my mind defaulted to "pip install" it. 

I've removed the package and all is still well. With that in mind, it shouldn't have any issues running on python2 as you've stated since that was the original blocker. Thanks again!
