### ISSUE TITLE
Errors responding to prompt at terminal

### ISSUE THREAD

**Issue by vreuter** [databio/refgenie#35]
From @michalstolarczyk :

One problem is a `SyntaxError` for an empty response:

when I hit Enter with no answer:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 360, in main
    rgc.pull_asset(args.genome, args.asset, genome_config_path, args.unpack)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 188, in pull_asset
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 188, in <listcomp>
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 220, in _pull_asset
    query_yes_no("Are you sure you want to download this large archive?"):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py", line 66, in query_yes_no
    return parse(_read_from_user() or default)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py", line 72, in _read_from_user
    return eval(input())
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

Another is a `NameError` for a nonempty response:

> ```
> [mstolarczyk@MichalsMBP refgenieserver]: refgenie pull -g hg38 -a epilog -u
> Are you sure you want to download this large archive? [y/N] y
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
>     sys.exit(main())
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 360, in main
>     rgc.pull_asset(args.genome, args.asset, genome_config_path, args.unpack)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 188, in pull_asset
>     genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 188, in <listcomp>
>     genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 220, in _pull_asset
>     query_yes_no("Are you sure you want to download this large archive?"):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py", line 66, in query_yes_no
>     return parse(_read_from_user() or default)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py", line 72, in _read_from_user
>     return eval(input())
>   File "<string>", line 1, in <module>
> NameError: name 'y' is not defined
> ```
> 
> it looks like there is some problem with the new version of `query_yes_no` function in `ubiquerg`. No answer is accepted

**Comment by vreuter** [comment]
Maybe OS- and/or (Python)version-specific: https://github.com/pepkit/ubiquerg/issues/9#issuecomment-498332895

**Comment by vreuter** [comment]
Possible that this is related to the conversion of `input()` to `eval(input())` that seems to be happening implicitly--it's not in source.

**Comment by nsheff** [comment]
Is this issue still pending?

**Comment by vreuter** [comment]
I never experienced it, so I don’t know.

**Comment by vreuter** [comment]
There’s a change in ubiquerg that may fix this, but that’s unconfirmed.

**Comment by michalstolarczyk** [comment]
I've experienced it before and now it works, closing..
