### ISSUE TITLE
New command: refgenie seek

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#50]
Here's an idea...

We can get an asset path from within python using refgenconf `get_asset(...)`... great if you're writing a pipeline in python, like we are. What if you're writing a shell pipeline?

It'd be nice to do:

```shell
genome='hg38'
 
# run fastq QC
...
# align with bowtie2
bowtie2 -x `refgenie seek -g $genome -a bowtie2_index` sample.bam ...

```

so the `refgenie seek` command would return your *local* asset location, wherever it is. this is nice because your pipeline now makes use of refgenie to locate assets so you're not hard-coding anything... it makes your pipeline more portable. This would be useful by any pipeline system that writes shell commands (cwl, wdl, etc).

In fact, we could even use this in pypiper pipelines instead of relying on the `refgenconf` API... I like it because it's universal and would be super simple to implement.

So, question: what's the name?

- `refgenie find`
- `refgenie seek`
- `refgenie getasset`
- `refgenie path`

votes?

**Comment by vreuter** [comment]
I like `path` second-least, but I think it makes the most sense. That preference is weak at best, though, so w/e others think.

**Comment by michalstolarczyk** [comment]
yeah, I agree that `path` makes the most sense, but on the other hand that would be the only positional argument that's not a verb.

so my vote goes to `seek`

**Comment by nsheff** [comment]
this was working, but now it's spitting out a bunch of other messages:

```
refgenie seek -g rCRS -a bowtie2_index -c test.yaml
Determined genome config: test.yaml
Getting asset 'bowtie2_index' for genome 'rCRS'
/ext/yeti/genomes/rCRS/indexed_bowtie2
```
