### ISSUE TITLE
double-slash in URL leads to problems

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#51]
If you put your genome_server as "http://refgenomes.databio.org/" (which is what we had on rivanna), then it makes a URL with a double-slash:

http://refgenomes.databio.org//assets

which returns "Not Found" instead of the list of assets.

**Comment by nsheff** [comment]
workaround: don't put a trailing slash on the genome_server URL in your config file.

but we should fix this somewhere.

**Comment by michalstolarczyk** [comment]
yeah, see: https://github.com/databio/refgenie/commit/5d99d9b753d7b3ed03150b3b15fbb5a4b9afc009
