### ISSUE TITLE
Usage docs page lacks subcommand detail

### ISSUE THREAD

**Issue by vreuter** [databio/refgenie#57]
Maybe this is intentional, though?

**Comment by vreuter** [comment]
`docs/usage.md`, that is

**Comment by nsheff** [comment]
not intentional... just not updated. we can use the same approach we used for looper here.

**Comment by vreuter** [comment]
OK. I see the script in the repo root. Do we just wait to update until release time?

**Comment by nsheff** [comment]
yeah. which is, basically, now :)
