### ISSUE TITLE
Require genome config for init?

### ISSUE THREAD

**Issue by vreuter** [databio/refgenie#59]
https://github.com/databio/refgenie/issues/58#issuecomment-502261069

**Comment by michalstolarczyk** [comment]
I don't quite understand how the config should be required. Do you mean that the path specified in `-c` or env var must to point to an _existing_ file? 

I'm confused since in #58 the path was provided in `-c`, the file just did not exist.

**Comment by vreuter** [comment]
This idea was spawned from #58 but does not intend to address it. As #58 shows (and previous implementation of `__main__` implied, `init` differs conceptually from the other commands). That difference _could_ be reflected in how we handle implementation of the CLI, as far as what's conditionally required.

**Comment by nsheff** [comment]
I disagree that it should be required, because I want to do this type of construction:

```
pip install --user refgenie
export REFGENIE='genomes.yaml'
refgenie init 
refgenie pull --genome hg38 --asset bowtie2
```

without having to type `genomes.yaml` twice. `refgenie init` should pick up the REFGENIE variable. Created issue #63 to reflect this.

**Comment by nsheff** [comment]
I suppose it could be:

```
pip install --user refgenie
export REFGENIE='genomes.yaml'
refgenie init  -c $REFGENIE
refgenie pull --genome hg38 --asset bowtie2
```

which is not too much I guess... so maybe I'm changing my mind.

In that case though the error message triggered by `refgenie init` should NOT say "or in an environment variable" as it does now (see #63)

**Comment by nsheff** [comment]
it's now required.
