### ISSUE TITLE
assets with multiple 'hooks'

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#71]
When designing the new recipe system, I realized some assets could have multiple 'hooks' to files.

I made the build system allow multiple keys to link to different paths within an asset:

https://github.com/databio/refgenie/blob/bc88cacee7d356f3a6206c73753d757df77d06ba/refgenie/asset_build_packages.py#L15-L21

here you see the asset name is `fasta`, but if you build `fasta`, then it *also* gives you `fai` and `chrom_sizes` assets. the world 'fasta' is used twice... once as the name of the asset, and then again as the one of the 3 keys. we're kind of overloading here.

we lack terminology for this kind of thing, and also, how should this be handled? RIght now, you say 'build fasta' and it will *actually* build 3 separate assets, each with its own entry in the config file.

this is a bit confusing, because "fai" is now considered an asset, but it's built not by `build fai`, but by `build fasta`... so we're using the word 'asset' to refer to 2 different things.

Should these instead be listed as some kind of 'sub-asset' within the `fasta` asset? and then sub-assets can also be retreived like assets? or maybe they should be retrievable like:

`refgenie seek -g genome -a fasta/chrom_sizes`

or something like that. do we just assume the `fasta` key is the default for `seek fasta` or require `seek fasta/fasta` in that case? Also, using the slashes may not be desirable because in the future we'll want to use them to indicate versions (`seek -a bowtie2_index/0.1.4`). 

we could introduce colons:  `seek -a fasta:fai`.

**Comment by vreuter** [comment]
I'm not familiar enough with use cases to know...chrom_sizes makes sense to permit access to, but would anyone ever to access the fasta index without also wanting the fasta? This doesn't answer the design question obviously, just probing for information.

**Comment by nsheff** [comment]
> but would anyone ever to access the fasta index without also wanting the fasta

I haven't ever needed it...

**Comment by michalstolarczyk** [comment]
resolved with "seek_keys" concept
