### ISSUE TITLE
change protocol for referring to assets

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#92]
Related to #62.

What do you think of following the approach of docker and referring to assets as: `{genome}/{asset}:{version}`. The genome is kind of like the namespace. It would simplify the interface. So,

```
refgenie pull hg38/bowtie2_index:1.0.4
```
instead of
```
refgenie pull -g hg38 -a bowtie2_index
```

One thought though: maybe we *do* want namespaces at some point... so it would be:

`{namespace}/{genome}::{asset}:{version}` or something. For example:

`ucsc/hg38::bowtie2_index:1.0` vs `ensembl/hg38::bowtie2_index:latest`.

The problem is this is 4 elements instead of 3, so we can't just use the basic `/` and `:`.

**Comment by nsheff** [comment]
Would be interested to hear what @johanneskoester thinks about this idea.

**Comment by nsheff** [comment]
@michalstolarczyk as I implement this I'm thinking about dropping support for the old `-g` and `-a` approach...it clutters the logic because the `--asset` arg needs to accommodate tags in order to make sense, and then it's essentially just a list of registry paths...

so the only advantage of the arg-based approach is that you can list multiple asset:tag combinations in a line. But is that really worth the complexity in the code? you can always just run the command over and over.

Maybe it is, because for building, then it all runs in 1 pipeline.

**Comment by michalstolarczyk** [comment]
ok, I'm on board. 

> so the only advantage of the arg-based approach is that you can list multiple asset:tag combinations in a line. But is that really worth the complexity in the code? you can always just run the command over and over.

we can allow for multiple registry path entries to allow pulling/building multiple versioned assets at once

**Comment by nsheff** [comment]
exactly. this is what I've now done!

**Comment by nsheff** [comment]
actually it's even better... I basically figured out a solution. the `-g` stayed, and `-a` became registry path.

so you can either do:
```
refgenie pull -g hg38 -a bowtie2_index:1.0 bowtie2_index:2.4 fasta`
```

or:
```
refgenie pull hg38/bowtie2_index:1.0 hg38/bowtie2_index:2.4 hg38/fasta
```

**Comment by michalstolarczyk** [comment]
that's awesome

**Comment by johanneskoester** [comment]
I would vote for even just take slashes and a colon at the end for the version:
`ucsc/hg38/bowtie2_index:1.0`. Seems less crowded to me. And yes, those namespaces are super important for some assets.
