### ISSUE TITLE
add setdefault command

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#95]
once https://github.com/databio/refgenconf/issues/50 is implemented, add `setdefault` command:

`refgenie setdefault -g genome -a asset -t tag`

**Comment by nsheff** [comment]
actually thinking about it now, the `-t` command doesn't make sense... it should just be appended to the asset, like

`-a asset:tag asset2:tag asset:tag2` ...
otherwise how do you associate assets with tags? so, tags should never be accepted separately.

**Comment by michalstolarczyk** [comment]
change of plans, see #101
